let guilds=[],selected=null,config={},page="overview";
const $=id=>document.getElementById(id),content=$("content");
const names={overview:"Overview",moderation:"Moderation",verification:"Verification",warnings:"Warnings",tickets:"Tickets",antiNuke:"Anti-Nuke",giveaways:"Giveaways",wordResponses:"Word Responses",welcome:"Welcome",erlc:"ERLC Sessions",logs:"Logs",premium:"Premium"};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function api(url,options={}){const r=await fetch(url,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(r.status===401){location.href="/";throw Error("Login required")}const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function field(label,path,value,type="text",full=false){const id="f_"+path.replaceAll(".","_"),cl=full?" full":"";if(type==="checkbox")return `<div class="field${cl}"><label class="check"><input id="${id}" data-path="${path}" type="checkbox" ${value?"checked":""}> ${esc(label)}</label></div>`;if(type==="textarea")return `<div class="field${cl}"><label for="${id}">${esc(label)}</label><textarea id="${id}" data-path="${path}">${esc(value??"")}</textarea></div>`;return `<div class="field${cl}"><label for="${id}">${esc(label)}</label><input id="${id}" data-path="${path}" type="${type}" value="${esc(value??"")}"></div>`}
function settings(title,desc,html){content.innerHTML=`<div class="card"><h2>${esc(title)}</h2><p class="muted">${esc(desc)}</p><div class="form-grid">${html}</div></div>`}
function render(){ $("pageTitle").textContent=names[page]||"Nexyl";document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));$("saveButton").style.display=["overview","warnings","logs","premium"].includes(page)?"none":"inline-block";
if(!selected){content.innerHTML='<div class="card"><h2>No manageable servers</h2><p class="muted">Add Nexyl to a server where you have Administrator permission.</p></div>';return}
if(page==="overview"){content.innerHTML=`<div class="card"><h2>${esc(selected.name)}</h2><p class="muted">Nexyl is connected. Select a section to configure your server.</p></div><div class="card"><h2>Quick setup</h2><p class="muted">Configure moderation, verification, welcome messages and more using the sidebar.</p></div>`;return}
if(page==="moderation")return settings("Moderation","Moderation settings and logs.",field("Enable moderation","moderation.enabled",config.moderation?.enabled,"checkbox")+field("Log channel ID","moderation.logChannelId",config.moderation?.logChannelId)+field("Warn role ID","moderation.warnRoleId",config.moderation?.warnRoleId)+field("Mute role ID","moderation.muteRoleId",config.moderation?.muteRoleId));
if(page==="verification")return settings("Verification","Configure !verify.",field("Enable verification","verification.enabled",config.verification?.enabled,"checkbox")+field("Channel ID","verification.channelId",config.verification?.channelId)+field("Role ID","verification.roleId",config.verification?.roleId)+field("Message","verification.message",config.verification?.message,"textarea",true));
if(page==="tickets")return settings("Tickets","Configuration placeholder for ticket automation.",field("Enable tickets","tickets.enabled",config.tickets?.enabled,"checkbox")+field("Category ID","tickets.categoryId",config.tickets?.categoryId)+field("Support role ID","tickets.supportRoleId",config.tickets?.supportRoleId));
if(page==="antiNuke")return settings("Anti-Nuke","Configuration placeholder for anti-nuke automation.",field("Enable Anti-Nuke","antiNuke.enabled",config.antiNuke?.enabled,"checkbox")+field("Threshold","antiNuke.threshold",config.antiNuke?.threshold,"number")+field("Window seconds","antiNuke.windowSeconds",config.antiNuke?.windowSeconds,"number"));
if(page==="giveaways")return settings("Giveaways","Configuration placeholder for giveaway automation.",field("Enable giveaways","giveaways.enabled",config.giveaways?.enabled,"checkbox"));
if(page==="wordResponses")return settings("Word Responses","Enter responses as JSON, e.g. {\"hello\":\"Hi!\"}.",field("Enable word responses","wordResponses.enabled",config.wordResponses?.enabled,"checkbox")+field("Responses JSON","wordResponses.responses",JSON.stringify(config.wordResponses?.responses||{},null,2),"textarea",true));
if(page==="welcome")return settings("Welcome","Welcome messages for new members.",field("Enable welcome","welcome.enabled",config.welcome?.enabled,"checkbox")+field("Channel ID","welcome.channelId",config.welcome?.channelId)+field("Message ({user}, {server})","welcome.message",config.welcome?.message,"textarea",true));
if(page==="erlc")return settings("ERLC Sessions","Stores ERLC settings; API integration is not implemented in this scaffold.",field("Enable ERLC","erlc.enabled",config.erlc?.enabled,"checkbox")+field("API key","erlc.apiKey",config.erlc?.apiKey)+field("Server code","erlc.serverCode",config.erlc?.serverCode));
if(page==="premium"){content.innerHTML='<div class="card"><h2>Nexyl Premium</h2><p class="muted">Premium session commands and future premium features.</p><a class="btn primary" href="https://discord.gg/tBrKBdsgMe" target="_blank" rel="noopener">Join Premium</a></div>';return}
if(page==="warnings"){content.innerHTML='<div class="card"><h2>Warnings</h2><p class="muted">Enter a Discord user ID.</p><div class="field"><label>User ID</label><input id="warningUserId" placeholder="123456789012345678"></div><br><button class="btn primary" id="loadWarnings">Load Warnings</button></div><div id="warningResults"></div>'; $("loadWarnings").onclick=async()=>{const id=$("warningUserId").value.trim();if(!id)return;try{const rows=await api(`/api/guild/${selected.id}/warnings/${encodeURIComponent(id)}`);$("warningResults").innerHTML=`<div class="card"><h2>Results</h2>${rows.length?`<div class="table-wrap"><table><tr><th>ID</th><th>Moderator</th><th>Reason</th><th>Date</th></tr>${rows.map(w=>`<tr><td>${w.id}</td><td>${esc(w.moderator_id)}</td><td>${esc(w.reason)}</td><td>${esc(w.created_at)}</td></tr>`).join("")}</table></div>`:"<p class='muted'>No warnings found.</p>"}</div>`}catch(e){alert(e.message)}};return}
if(page==="logs"){content.innerHTML='<div class="card"><h2>Logs</h2><p class="muted">Loading…</p></div>';api(`/api/guild/${selected.id}/logs`).then(rows=>{content.innerHTML=`<div class="card"><h2>Logs</h2><div class="table-wrap"><table><tr><th>Action</th><th>User</th><th>Moderator</th><th>Details</th><th>Date</th></tr>${rows.map(l=>`<tr><td>${esc(l.action)}</td><td>${esc(l.user_id)}</td><td>${esc(l.moderator_id)}</td><td>${esc(l.details)}</td><td>${esc(l.created_at)}</td></tr>`).join("")}</table></div></div>`}).catch(e=>content.innerHTML=`<div class="card">${esc(e.message)}</div>`)}}
function setPath(o,path,value){const keys=path.split(".");let t=o;for(const k of keys.slice(0,-1)){if(!t[k]||typeof t[k]!=="object")t[k]={};t=t[k]}t[keys.at(-1)]=value}
async function save(){try{const next=structuredClone(config);document.querySelectorAll("[data-path]").forEach(el=>{let v=el.type==="checkbox"?el.checked:el.type==="number"?Number(el.value):el.value;if(el.dataset.path==="wordResponses.responses"){try{v=JSON.parse(el.value||"{}")}catch{throw Error("Responses JSON is invalid.")}}setPath(next,el.dataset.path,v)});config=await api(`/api/guild/${selected.id}/config`,{method:"PUT",body:JSON.stringify(next)});alert("Saved.");render()}catch(e){alert(e.message)}}
async function loadGuild(id){selected=guilds.find(g=>g.id===id)||null;if(selected){config=await api(`/api/guild/${selected.id}/config`);render()}}
async function init(){const me=await api("/api/me");$("userLabel").textContent=me.username||"Discord user";guilds=await api("/api/guilds");$("serverPicker").innerHTML=guilds.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join("")||'<option value="">No manageable servers</option>';if(guilds.length)await loadGuild(guilds[0].id);else render()}
$("serverPicker").addEventListener("change",e=>loadGuild(e.target.value));$("saveButton").addEventListener("click",save);document.querySelectorAll("#nav button").forEach(b=>b.addEventListener("click",()=>{page=b.dataset.page;render();$("sidebar").classList.remove("open")}));$("mobileMenu").addEventListener("click",()=>$("sidebar").classList.toggle("open"));init().catch(e=>{console.error(e);content.innerHTML=`<div class="card"><h2>Dashboard error</h2><p class="muted">${esc(e.message)}</p></div>`});
